apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netcup-failover-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netcup-failover-controller
subjects:
  - kind: ServiceAccount
    name: netcup-failover-controller
    namespace: netcup-system
