apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netcup-failover-controller.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "netcup-failover-controller.labels" . | nindent 4 }}
